
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login-seguranca
    username: seguranca
    password: seguranca
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ifframephoto@gmail.com
    password: grsvwlmoeeccbpes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always

spring.jackson.default-property-inclusion: non_null

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
